export const metadata = { title: 'Privacy and Data Retention', description: 'How AMSMA collects, uses, protects and retains membership application data.' };

export default function PrivacyPage() {
  return <><header className="ll-page-hero"><div className="ll-page-hero-inner"><p className="ll-eyebrow">Privacy</p><h1 className="ll-title">Privacy and Data Retention Notice.</h1><p className="ll-lede">This notice explains how AMSMA handles personal and organisation data submitted through its membership process.</p></div></header><section className="ll-section"><div className="ll-section-inner ll-policy-layout"><aside className="ll-policy-summary"><p className="ll-kicker">Consent statement</p><h2 className="ll-heading">Know how your data will be used.</h2><p>By submitting a membership application, you confirm that the information is accurate and consent to AMSMA processing it for the purposes described below.</p><p className="ll-policy-date">Last updated: 1 September 2026</p></aside><div className="ll-policy-content">
    <Policy title="Data we collect">We may collect the applicant&apos;s name, email address, telephone number, role, organisation name, registration details, address, PAN, authorised-signatory details, membership category, company-proof link, proposer and seconder details, application history, payment status and related correspondence.</Policy>
    <Policy title="Why we use it">We use this data to verify eligibility, review and decide the application, contact the applicant, collect an approved subscription, activate membership, maintain the Register of Members, keep financial and governance records, prevent misuse and respond to questions or disputes.</Policy>
    <Policy title="Who can access it">Access is limited to authorised AMSMA committee members and personnel who need the information for the membership process. Relevant data may also be processed by service providers that host the application, communications or payment systems, and by professional advisers or public authorities when required by law. AMSMA does not sell membership application data.</Policy>
    <section><h3>How long we keep it</h3><ul className="list-disc pl-5"><li>Incomplete applications may be deleted 90 days after the last activity.</li><li>Withdrawn or declined applications may be retained for up to 12 months after the final decision.</li><li>Approved member data is retained while membership is active. Core legal, governance, accounting and payment records are retained as required by law.</li><li>Supporting documents and links that are no longer required are deleted or access-restricted as soon as reasonably practical.</li></ul><p>When data is no longer required for these purposes or by law, it is deleted or anonymised.</p></section>
    <Policy title="Your choices and rights">You may ask to access or correct your data, withdraw consent, or request deletion of data that AMSMA no longer needs. Withdrawal does not affect processing that took place before withdrawal and may prevent AMSMA from completing an application or continuing a service that needs the data.</Policy>
    <Policy title="Security">AMSMA uses reasonable administrative and technical safeguards to limit unauthorised access, loss, misuse or disclosure. No online service can guarantee absolute security. Applicants should submit only the information requested by the form.</Policy>
    <section><h3>Privacy contact</h3><p>Send privacy questions, corrections, withdrawal requests or complaints to <a href="mailto:info@amsma.in">info@amsma.in</a>. Include enough information for AMSMA to identify the application and verify the requester.</p></section>
  </div></div></section></>;
}

function Policy({ title, children }: { title: string; children: React.ReactNode }) {
  return <section><h3>{title}</h3><p>{children}</p></section>;
}
