ALTER TABLE "PortalUser" ADD COLUMN "forumPostingSuspended" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ForumTopic" ADD COLUMN "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ForumTopic" ADD COLUMN "isPinned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ForumPost" ADD COLUMN "isDeleted" BOOLEAN NOT NULL DEFAULT false;
