import Link from 'next/link';
import { TIERS_LIST, formatInr } from '@/config/membership';

export const metadata = { title: 'Membership', description: 'AMSMA membership categories, eligibility, annual subscriptions and application process.' };

export default function MembershipPage() {
  return <>
    <header className="ll-page-hero"><div className="ll-page-hero-inner"><p className="ll-eyebrow">Membership</p><h1 className="ll-title">Join a community shaping India&apos;s aggregate industry.</h1><p className="ll-lede">Membership is open to eligible businesses, institutions and individuals engaged in the aggregate and M sand sector. Categories, eligibility and subscriptions are governed by Rule 4 of the Association&apos;s Rules &amp; Regulations.</p></div></header>
    <section className="ll-section ll-alt"><div className="ll-section-inner"><p className="ll-kicker">Membership categories</p><h2 className="ll-heading">Choose the category that fits.</h2><div className="grid md:grid-cols-2 gap-4 mt-8">{TIERS_LIST.map(tier => <article className="flex flex-col border border-black/20 bg-[#f2ede1] p-6" key={tier.id}><p className="ll-kicker">{tier.category}</p><h3 className="text-2xl font-bold leading-tight">{tier.label}</h3><p className="my-3 mb-6">{tier.eligibility}</p><div className="mt-auto border-t border-black/20 pt-4 text-3xl font-bold">{formatInr(tier.annualFeeRupees)} <span className="font-sans text-xs font-semibold text-black/60">/ year</span></div><p className="mt-2 font-sans text-xs font-semibold text-black/60">Voting weightage: {tier.votingWeightage} · {tier.allowsIndividuals ? 'Individuals eligible' : 'Corporate bodies only'}</p></article>)}</div>
      <div className="mx-auto mt-8 max-w-3xl text-center"><Link className="ll-button ll-button-solid" href="/membership/apply">Apply for Membership</Link><p className="mt-4 text-sm">Applications require a proposer and seconder and are reviewed by the Managing Committee. Payment is collected only after approval.</p></div>
      <aside className="mx-auto mt-8 max-w-4xl border border-black/20 bg-[#f2ede1] p-6"><h3 className="text-xl font-bold">How we use application data</h3><p className="mt-3">The application asks for identity, contact, organisation, PAN, supporting-document, proposer and seconder details. AMSMA uses this information only to assess and process membership, communicate with the applicant, collect an approved subscription and maintain membership records.</p><p className="mt-3">You must give clear consent before you submit the form. Read the <Link href="/privacy">Privacy and Data Retention Notice</Link> before you continue.</p></aside>
    </div></section>
    <section className="ll-section"><div className="ll-section-inner"><p className="ll-kicker">How it works</p><h2 className="ll-heading">Four steps to active membership.</h2><div className="grid md:grid-cols-2 gap-4 mt-8"><Stage number="01" title="Submit the application">Provide the category, organisation details, PAN, address, authorised signatory, a company-proof link, and two existing members as proposer and seconder.</Stage><Stage number="02" title="Committee review">The Managing Committee reviews the application through secure links. Admission requires the required committee majority.</Stage><Stage number="03" title="Pay after approval">Approved applicants receive a secure payment link for the correct annual subscription. The link is valid for 14 days.</Stage><Stage number="04" title="Activate membership">After verified payment, the applicant is entered in the Register of Members and receives an AMSMA member number.</Stage></div></div></section>
    <section className="ll-section ll-dark"><div className="ll-section-inner ll-content-grid"><div><p className="ll-eyebrow">Ready to apply?</p><h2 className="ll-heading">Prepare the required details.</h2></div><div className="ll-prose"><p>Have the organisation&apos;s registration details, PAN, registered address, signatory information and a shareable company-proof document link ready.</p><p>You will also need the names and email addresses of two different existing committee members who will act as proposer and seconder.</p><div className="ll-button-row"><Link className="ll-button ll-button-solid" href="/membership/apply">Start Application</Link></div></div></div></section>
  </>;
}

function Stage({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <article className="flex gap-4 border-t border-black/20 bg-[#f2ede1] p-5"><span className="ll-kicker shrink-0">{number}</span><div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2">{children}</p></div></article>;
}
